name: Update Docker Hub Description
on:
  push:
    branches:
      - master
      - develop
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  pull_request:
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: grokability/dockerhub-description
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: snipe/snipe-it
          readme-filepath: ./README.md
