name: Install

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, fileinfo, json, mbstring, pdo
          coverage: none

      - name: Install Composer dependencies
        run: composer install --dev --no-interaction --no-progress
