name: Lint

on:
  push:
#    branches: [ "main" ]
  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: "${{ matrix.php }}"

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - # Lint
        name: Check PHP syntax errors
        uses: overtrue/phplint@3.4.0
